"""project_label tabel

Revision ID: 0180cf9bd7df
Revises: 4924431a234f
Create Date: 2022-07-25 00:51:03.658739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0180cf9bd7df"
down_revision = "4924431a234f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projectlabel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("simple", "rectangle", "polygon", name="labeltype"),
            nullable=True,
        ),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["project.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("projectlabel")
    # ### end Alembic commands ###
